#!/bin/bash

if [ "x$1" == "x-h" ];then
  echo "usage: main <input_file> [n_gpu_layer]"
  exit 1
elif [ "x$1" == "x" ]; then
  echo "enter a png file"
  exit 2
else

if [ "-ngl $2" == "-ngl " ];then
  is_ngl=""
else
  is_ngl="-ngl $2"
fi

  convert $1 -colorspace Gray -threshold 35% questions/output_image.png
  tesseract questions/output_image.png questions/ocr -l deu

  inputFile='questions/ocr.txt'
  text=$(cat $inputFile)

  rm output.txt
  rm output.pdf

  llama-cli -m /var/models/mistral-7b-instruct-v0.2.Q8_0.gguf \
  --in-prefix "solve the test in german and with short sentences and don't add your own questions" \
  -p "$text\n\nAnswers:\n\n" -no-cnv -n 512 $is_ngl >> output.txt

  pandoc output.txt -o output.pdf
fi
