#!/bin/bash

if [ "x$1" == "x" ]; then
  echo "enter a png file"
  exit 2
else

  convert $1 -colorspace Gray -threshold 35% questions/output_image.png
  tesseract questions/output_image.png questions/ocr -l deu


  inputFile='questions/ocr.txt'
  text=$(cat $inputFile)

  llama-cli -m /var/models/mistral-7b-instruct-v0.2.Q8_0.gguf \
  --in-prefix "solve the test in german and with short sentences and don't add your own questions" \
  -p "$text\n\nAnswers:\n\n" -no-cnv
fi
